### ISSUE TITLE
Need to show the evolution of the fitness

### ISSUE THREAD

**Issue by bergel** [OBJECTSEMANTICS/SmallSuiteGenerator#13]
We should use Roassal2 to display this graphic. You can take inspiration from https://agileartificialintelligence.github.io/book/build/10-GeneticAlgorithm.html

**Comment by Lin777** [comment]
![image](https://user-images.githubusercontent.com/15729309/71692399-20592b80-2d80-11ea-9c72-449cbc3656ec.png)
 @andreina-covi  has already generated this graphic, I'm not sure if this is what you mean with this Issue since the link is broken
