### ISSUE TITLE
Fix broken tests

### ISSUE THREAD

**Issue by Lin777** [OBJECTSEMANTICS/SmallSuiteGenerator#133]
#########################

# 7 tests did not pass: #

#########################

STypeInfoTest
e90ab2_f054

 ✗ #testAsTypeInfoSFoo (771ms)
828325_f054

 ✗ #testAsTypeInfoScalars (80ms)
fe3bec_f054

 ✗ #testJoinWith (182ms)
54f90c_f054

 ✗ #testType (203ms)

SSTestShifterTest
d88a53_f054

 ✗ #testAddMessageWithTwoDeepScalarSFoo (16ms)
44f613_f054

 ✗ #testAddMessageWithTwoDeepScalarSStack (15ms)

SGAEngineTest
fa2c7b_f054

 ✗ #testRunOnPackagesSSTeacherUsingMethodCoverage (4377ms)

**Comment by daniapq** [comment]
SGAEngineTest run correctly
