### ISSUE TITLE
Visualization error to try of finding targetClassName on fitness

### ISSUE THREAD

**Issue by andreina-covi** [OBJECTSEMANTICS/SmallSuiteGenerator#167]
I ran the script: 

```
|typeInfo aBlock generated |
aBlock := [| canvas shapes color |
	canvas := RSCanvas new.
	
	color := RSColorPalette sequential bupu3.
	shapes := (1 to: 20) collect: [ :m |
		RSBox new
			size: 10;
			model: m;
			draggable;
			withBorder;
			color: (color scale: m);
			yourself.
		 ].
	RSEdgeBuilder line
		shapes: shapes;
		canvas: canvas;
		connectFrom: [ :n | n // 2 ].
	canvas edges do: #withBorder.
	canvas addAll: shapes.
	canvas shapes @ RSHighlightable defaultRed.
	RSClusterLayout on: shapes.
	canvas zoomToFit.
	canvas].
typeInfo := STypeInfo asTypeInfo: (
        SSTypeCollector profile: aBlock onPackagesMatching: 'Roassal3*').

generated := RSBox createTestCaseConfigWithName: 'RSBoxTestGenerated'.

generated addTypeInfo: typeInfo withKey: 'rsbox';
	typeInfo: 'rsbox';
	fitness: #statement;
	numberOfGenerations: 10;
	numberOfStatements: 30;
	populationSize: 20;
	stopIterations: 5;
	targetPackageRegex: 'Roassal3*';
	outputPackageName: 'Generated';
	setUpMethod: 'setUp
	^ self';
	tearDownMethod: 'tearDown
	^ self'.
```
after I ran: 
```
(STestCaseFactoryPharo from: RSBoxTestGenerated )
	generateViews;
	seedBlock: aBlock;
    createTestCases;
    yourself.
```
and I got a error. The error says: "KeyNotFound: key #RSBox not found in Dictionary".
It is because the targetClassName: `RSBox` is not found on fitness. Fitness just contains `RSBoundingShape` key (which is a superclass of RSBox),

**Comment by Lin777** [comment]
I tried to reproduce the error however I couldn't replicate it, the provided script runs correctly

**Comment by daniapq** [comment]
The error only occurs when you select the GenerationEvolution tab after generate tests. In SGAViz class, if you check the logs, only the first SGALog object not contains RSBox and this is what causes the error to be raised. I used other run seeds and they worked perfectly. I'll leave this issue open until we make the changes to the tool. Possibly with the changes we make, this problem will be solved
