### ISSUE TITLE
Should have a unique random number generation

### ISSUE THREAD

**Issue by bergel** [OBJECTSEMANTICS/SmallSuiteGenerator#45]
We should be able to provide a random number generator to `STestCaseFactory`. Algo como `STestCaseFactory new random: (Random seed: 42)`.

In that case, if we execute twice the same test generation, we should obtain the very very same generated tests.

**Comment by Lin777** [comment]
Fixed in https://github.com/OBJECTSEMANTICS/SmallSuiteGenerator/commit/c66d97163213494b73806057bb082e46bf1a501e
