### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by jpsandoval** [OBJECTSEMANTICS/SmallSuiteGenerator#98]
First time that I use the installer it throws and error. I executed again, and then work!... but this messages appear in the console
tally is Undeclared
SMemo is Undeclared
RSYLabelDecoration is Undeclared
RSHighlightEvent is Undeclared
Margin is Undeclared
Monitor is Undeclared
SubscriptOutOfBounds is Undeclared
RSGroup is Undeclared
S2Profiler is Undeclared
RSVerticalLineLayout is Undeclared
RSGridLayout is Undeclared
KeyNotFound is Undeclared
RSVerticalTick is Undeclared
RSSparkCircle is Undeclared
RSComposite is Undeclared
RSHorizontalTick is Undeclared
RPackage is Undeclared
TestCase is Undeclared
RSUnHighlightEvent is Undeclared
RSEdgeBuilder is Undeclared
STON is Undeclared
RSLinePlot is Undeclared
RSPolyline is Undeclared
RSCanvasController is Undeclared
RSChart is Undeclared
RSLine is Undeclared
RSBox is Undeclared
OrderedDictionary is Undeclared
RSLabel is Undeclared
TinyLogger is Undeclared
SSTypeCollector is Undeclared
RSLocation is Undeclared
RSCanvas is Undeclared
RSLegend is Undeclared
RSBorder is Undeclared
NeoCSVWriter is Undeclared
RSHorizontalLineLayout is Undeclared
NSScale is Undeclared
RBParser is Undeclared
SystemVersion is Undeclared
RSHighlightable is Undeclared
LinearGradientPaint is Undeclared
Color is Undeclared
Spy2 is Undeclared

This means that there are dependencies that are not there... this may cause several errors....

**Comment by Lin777** [comment]
tally is Undeclared
STON is Undeclared
KeyNotFound is Undeclared
I already cleaned some loading errors, still missing:
Color is Undeclared
Monitor is Undeclared
RPackage is Undeclared
SSTypeCollector is Undeclared
OrderedDictionary is Undeclared
